### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by konno-tech** [konno-tech/protospace-31063#1]
https://protospace-31063.herokuapp.com/

**Comment by mutorisa** [comment]
今野さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正が必要な項目]**
＜ユーザー詳細ページ機能：各ページのユーザー名をクリックすると、ユーザーの詳細ページへ遷移する＞
**→現状、ユーザーによって（ll）はユーザー詳細ページに遷移されずエラーが出てしまう状態です。どのユーザー名をクリックしても正常にユーザー詳細ページへ遷移されるよう実装しましょう。**

＜エラー画面＞
<img width="572" alt="スクリーンショット 2020-10-27 10 22 13" src="https://user-images.githubusercontent.com/65144927/97246081-d75af200-183f-11eb-990f-b32800f1374b.png">

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7
※新しいissueを作っていただく必要はありません

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルにお送りいたします。
今しばらくお待ちください。
